import test from "node:test";
import assert from "node:assert/strict";
import http from "node:http";
import { createAppServer } from "../server.mjs";

// A configured environment carrying one extra secret, so every response can be
// checked for leaking it. The values are fictional.
const CONFIGURED = Object.freeze({
  SUPABASE_URL: "http://127.0.0.1:57321",
  SUPABASE_PUBLISHABLE_KEY: "sb_publishable_fictional_value",
  AUTH_RESEND_COOLDOWN_SECONDS: "65",
  VITALLY_TEST_ADMIN_KEY: "sb_secret_this_must_never_be_served",
  DATABASE_URL: "postgresql://postgres:fictional@127.0.0.1:57322/postgres",
});

// Raw requests, never `fetch`: a URL parser would resolve `..` before the
// request left, and it is precisely the unresolved path the server must refuse.
const request = (port, path, method = "GET") =>
  new Promise((resolve, reject) => {
    const call = http.request(
      { host: "127.0.0.1", port, path, method },
      (response) => {
        let body = "";
        response.setEncoding("utf8");
        response.on("data", (chunk) => (body += chunk));
        response.on("end", () =>
          resolve({
            status: response.statusCode,
            headers: response.headers,
            body,
          }),
        );
      },
    );
    call.on("error", reject);
    call.end();
  });

async function withServer(env, body) {
  const server = createAppServer({ env });
  await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
  try {
    const address = server.address();
    assert.equal(address.address, "127.0.0.1", "the demo binds to loopback");
    await body(address.port);
  } finally {
    await new Promise((resolve) => server.close(resolve));
  }
}

test("the allowlisted browser files are served with their type", async () => {
  await withServer(CONFIGURED, async (port) => {
    const expected = [
      ["/", "text/html; charset=utf-8"],
      ["/index.html", "text/html; charset=utf-8"],
      ["/src/app.mjs", "text/javascript; charset=utf-8"],
      ["/src/styles.css", "text/css; charset=utf-8"],
      ["/src/auth.mjs", "text/javascript; charset=utf-8"],
      ["/src/supabase-store.mjs", "text/javascript; charset=utf-8"],
      ["/src/vendor/supabase.mjs", "text/javascript; charset=utf-8"],
      ["/public-config.json", "application/json; charset=utf-8"],
    ];
    for (const [path, type] of expected) {
      const response = await request(port, path);
      assert.equal(response.status, 200, path);
      assert.equal(response.headers["content-type"], type, path);
      assert.equal(response.headers["x-content-type-options"], "nosniff", path);
      assert.ok(response.body.length > 0, path);
      // No response, whatever it serves, may carry an operator secret.
      for (const secret of [
        CONFIGURED.VITALLY_TEST_ADMIN_KEY,
        CONFIGURED.DATABASE_URL,
      ])
        assert.ok(!response.body.includes(secret), `${path} leaked a secret`);
    }
    // The committed vendor bundle is what is served, not a rebuild.
    const vendor = await request(port, "/src/vendor/supabase.mjs");
    assert.match(vendor.body, /^\/\/ Generated by tools\/build\.mjs/);
    assert.match(vendor.body, /@supabase\/supabase-js \d+\.\d+\.\d+/);
  });
});

test("the public config carries the four documented keys and nothing else", async () => {
  await withServer(CONFIGURED, async (port) => {
    const response = await request(port, "/public-config.json");
    const config = JSON.parse(response.body);
    assert.deepEqual(Object.keys(config).toSorted(), [
      "authResendCooldownSeconds",
      "configured",
      "supabasePublishableKey",
      "supabaseUrl",
    ]);
    assert.deepEqual(config, {
      configured: true,
      supabaseUrl: CONFIGURED.SUPABASE_URL,
      supabasePublishableKey: CONFIGURED.SUPABASE_PUBLISHABLE_KEY,
      authResendCooldownSeconds: 65,
    });
  });
});

test("an unconfigured server starts and reports the absence", async () => {
  // No .env.local at all: the app still loads and shows its setup screen.
  for (const env of [
    {},
    { SUPABASE_URL: CONFIGURED.SUPABASE_URL },
    { SUPABASE_PUBLISHABLE_KEY: CONFIGURED.SUPABASE_PUBLISHABLE_KEY },
    { SUPABASE_URL: "  ", SUPABASE_PUBLISHABLE_KEY: "  " },
  ])
    await withServer(env, async (port) => {
      const response = await request(port, "/public-config.json");
      assert.equal(response.status, 200);
      assert.deepEqual(JSON.parse(response.body), { configured: false });
      assert.equal(
        (await request(port, "/index.html")).status,
        200,
        "the demo still serves its page",
      );
    });
});

test("the resend cooldown is a positive integer or the documented default", async () => {
  const expected = [
    ["65", 65],
    ["90", 90],
    ["1", 1],
    [undefined, 65],
    ["", 65],
    ["0", 65],
    ["-30", 65],
    ["65.5", 65],
    ["sixty-five", 65],
    ["65s", 65],
    [" 70 ", 70],
  ];
  for (const [value, seconds] of expected)
    await withServer(
      { ...CONFIGURED, AUTH_RESEND_COOLDOWN_SECONDS: value },
      async (port) => {
        const config = JSON.parse(
          (await request(port, "/public-config.json")).body,
        );
        assert.equal(config.authResendCooldownSeconds, seconds, String(value));
      },
    );
});

test("private files, tooling and traversal are all not found", async () => {
  await withServer(CONFIGURED, async (port) => {
    const refused = [
      "/.env.local",
      "/.env.test",
      "/.env.admin",
      "/.vitally-targets.json",
      "/supabase/migrations/001_identity_and_cases.sql",
      "/tests/database.mjs",
      "/tests/support/database-fixture.mjs",
      "/tools/admin/migrate.mjs",
      "/tools/build.mjs",
      "/package.json",
      "/package-lock.json",
      "/server.mjs",
      "/../server.mjs",
      "/src/../server.mjs",
      "/src/vendor/../app.mjs",
      "/src/vendor/../../server.mjs",
      "/%2e%2e/server.mjs",
      "/src/%2e%2e/server.mjs",
      "/src/..%2fserver.mjs",
      "/src/",
      "/src/vendor/",
      "/src/app.mjs/",
      "/node_modules/@supabase/supabase-js/package.json",
      "/docs/setup.md",
      "/.git/config",
    ];
    for (const path of refused) {
      const response = await request(port, path);
      assert.equal(response.status, 404, path);
      assert.ok(!response.body.includes("SUPABASE"), path);
      assert.ok(
        !response.body.includes(CONFIGURED.VITALLY_TEST_ADMIN_KEY),
        path,
      );
    }
  });
});

test("only GET and HEAD reach the allowlist", async () => {
  await withServer(CONFIGURED, async (port) => {
    for (const path of ["/", "/index.html", "/public-config.json", "/src/app.mjs"])
      for (const method of ["POST", "PUT", "DELETE", "PATCH"]) {
        const response = await request(port, path, method);
        assert.equal(response.status, 405, `${method} ${path}`);
        assert.equal(response.headers.allow, "GET, HEAD", `${method} ${path}`);
      }
    // A method that is refused anyway must not disclose what exists.
    assert.equal((await request(port, "/.env.local", "POST")).status, 404);
    const head = await request(port, "/index.html", "HEAD");
    assert.equal(head.status, 200);
    assert.equal(head.headers["x-content-type-options"], "nosniff");
    assert.equal(head.body, "");
  });
});

test("a query string does not change what is served or refused", async () => {
  await withServer(CONFIGURED, async (port) => {
    assert.equal((await request(port, "/index.html?v=2")).status, 200);
    assert.equal((await request(port, "/public-config.json?v=2")).status, 200);
    assert.equal((await request(port, "/server.mjs?v=2")).status, 404);
  });
});
