// Builds the one committed browser vendor file, `src/vendor/supabase.mjs`.
//
// The public demo is served from the repository root as plain static files,
// with no build step at request time (Ruling R33). So the SDK is bundled ahead
// of time into a file that is committed like any other source file, and
// `index.html` keeps its relative `./src/...` paths. Nothing of this project is
// bundled: the entry re-exports `createClient` alone, and the application
// modules take an injected client instead of importing the SDK.
//
// Run with:
//   node tools/build.mjs        (npm run build:vendor)
import { build } from "esbuild";
import { readFile, stat } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const entry = path.join(root, "tools", "vendor-entry.mjs");
const outfile = path.join(root, "src", "vendor", "supabase.mjs");

const installedVersion = async (name) =>
  JSON.parse(
    await readFile(
      path.join(root, "node_modules", ...name.split("/"), "package.json"),
      "utf8",
    ),
  ).version;

// The exact pinned versions go into the banner, so a reviewer reading the
// committed artefact can tell which SDK build it contains without rebuilding.
export async function buildVendorBundle() {
  const sdk = await installedVersion("@supabase/supabase-js");
  const bundler = await installedVersion("esbuild");
  const banner = [
    "// Generated by tools/build.mjs. Do not edit by hand.",
    `// @supabase/supabase-js ${sdk}, bundled with esbuild ${bundler}.`,
    "// Rebuild with: npm run build:vendor",
  ].join("\n");
  await build({
    entryPoints: [entry],
    bundle: true,
    format: "esm",
    platform: "browser",
    minify: true,
    outfile,
    banner: { js: banner },
  });
  return { sdk, bundler, outfile, bytes: (await stat(outfile)).size };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const result = await buildVendorBundle();
  console.log(
    `Bundled @supabase/supabase-js ${result.sdk} with esbuild ${result.bundler}: ` +
      `${path.relative(root, result.outfile)} (${result.bytes} bytes)`,
  );
}
