// npm run build:hant — writes src/zh-hant.mjs; `-- --check` only compares.
import { readFile, writeFile } from "node:fs/promises";
import { pathToFileURL } from "node:url";
import * as OpenCC from "opencc-js";
import { collectSimplified } from "./hant-sources.mjs";
import OVERRIDES from "./hant-overrides.mjs";

const TARGET = new URL("../src/zh-hant.mjs", import.meta.url);

export function convertAll(strings, converter, overrides) {
  const out = {};
  for (const simplified of strings) {
    let traditional = converter(simplified);
    for (const { from, to } of overrides) {
      if (!simplified.includes(from)) continue;
      traditional = traditional.split(converter(from)).join(to);
    }
    out[simplified] = traditional;
  }
  // OpenCC can convert a fragment on its own differently from inside the full
  // sentence, so an override's search can miss. Every override must land.
  for (const { from, to } of overrides) {
    const wanted = strings.filter((s) => s.includes(from));
    if (wanted.length && !wanted.every((s) => out[s].includes(to)))
      throw new Error(`Override ${from} → ${to} did not apply to every string that has it`);
    if (!wanted.length) throw new Error(`Override ${from} matches no source string`);
  }
  return out;
}

export function renderMap(map) {
  const lines = Object.keys(map)
    .sort()
    .map((key) => `  ${JSON.stringify(key)}: ${JSON.stringify(map[key])},`);
  return `// Generated by tools/build-hant.mjs (npm run build:hant). Do not edit.
// Simplified source string → Traditional (OpenCC, common Traditional, plus
// tools/hant-overrides.mjs). Keys are exact source strings (spec §4).
export default Object.freeze({
${lines.join("\n")}
});
`;
}

async function main() {
  const converter = OpenCC.Converter({ from: "cn", to: "t" });
  const text = renderMap(convertAll(collectSimplified(), converter, OVERRIDES));
  if (process.argv.includes("--check")) {
    const committed = await readFile(TARGET, "utf8").catch(() => "");
    if (committed !== text) {
      console.error("src/zh-hant.mjs is out of date: run npm run build:hant");
      process.exit(1);
    }
    return;
  }
  await writeFile(TARGET, text);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) await main();
