// Builds the two committed browser vendor files:
//   `src/vendor/supabase.mjs` from `tools/vendor-entry.mjs` (the Supabase SDK),
//   `src/vendor/pdf-lib.mjs` from `tools/vendor-pdf-entry.mjs` (pdf-lib and
//   @pdf-lib/fontkit, for the draft Form 13614-C; spec 2026-10-04 §7.3).
//
// The public demo is served from the repository root as plain static files,
// with no build step at request time (Ruling R33). So each library is bundled
// ahead of time into a file that is committed like any other source file, and
// `index.html` keeps its relative `./src/...` paths. Nothing of this project is
// bundled: each entry only re-exports library names, and the application
// modules take injected objects instead of importing the libraries.
//
// Run with:
//   node tools/build.mjs        (npm run build:vendor)
import { build } from "esbuild";
import { readFile, stat } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

const installedVersion = async (name) =>
  JSON.parse(
    await readFile(
      path.join(root, "node_modules", ...name.split("/"), "package.json"),
      "utf8",
    ),
  ).version;

async function bundle({ entry, outfile, libraries }) {
  const bundler = await installedVersion("esbuild");
  const versions = [];
  for (const name of libraries)
    versions.push(`${name} ${await installedVersion(name)}`);
  const banner = [
    "// Generated by tools/build.mjs. Do not edit by hand.",
    `// ${versions.join(", ")}, bundled with esbuild ${bundler}.`,
    "// Rebuild with: npm run build:vendor",
  ].join("\n");
  await build({
    entryPoints: [path.join(root, "tools", entry)],
    bundle: true,
    format: "esm",
    platform: "browser",
    minify: true,
    outfile: path.join(root, "src", "vendor", outfile),
    banner: { js: banner },
  });
  const written = path.join(root, "src", "vendor", outfile);
  return { versions, bundler, outfile: written, bytes: (await stat(written)).size };
}

// The exact pinned versions go into each banner, so a reviewer reading the
// committed artefact can tell which build it contains without rebuilding.
export const buildVendorBundle = () =>
  bundle({
    entry: "vendor-entry.mjs",
    outfile: "supabase.mjs",
    libraries: ["@supabase/supabase-js"],
  });

export const buildPdfBundle = () =>
  bundle({
    entry: "vendor-pdf-entry.mjs",
    outfile: "pdf-lib.mjs",
    libraries: ["pdf-lib", "@pdf-lib/fontkit"],
  });

if (import.meta.filename === process.argv[1]) {
  for (const result of [await buildVendorBundle(), await buildPdfBundle()])
    console.log(
      `Bundled ${result.versions.join(", ")} with esbuild ${result.bundler}: ` +
        `${path.relative(root, result.outfile)} (${result.bytes} bytes)`,
    );
}
